### ISSUE TITLE
Wrong style version in functions.php

### ISSUE THREAD

**Issue by marcelstoer** [ScottSmith95/Decode#50]
The style version in `functions.php` wasn't updated for 3.0.8 and 3.0.9. I doubt that was intentional.

https://github.com/ScottSmith95/Decode/blob/master/functions.php#L137 shows it's still at 3.0.7. 

I guess it's generally quite unfortunate that the version is hard-coded in at least four places - and is thus prone to be inconsistent: `package.json`, `style.css` and twice in `functions.php`. You could away with the last two if you used `wp_get_theme()->get('Version')` instead. I don't know, however, what the behavior would be if someone built a child theme for Decode. Would you get the Decode version or the child theme version?

**Comment by ScottSmith95** [comment]
Child themes will continue to use the child theme styles, regardless of style. I like this workaround, but this is intentional, the CSS hasn't been changed significantly since version 3.0.7, so I didn't want to force a cache-bust on users. I update the stylesheet version when needed, but not every version alters the CSS off the theme.
